#!/bin/sh

if [ -z "$WITHGNUPLOTOUTPUT_GNUPLOT_COMMAND" -o -z "$WITHGNUPLOTOUTPUT_TERMINAL_SETTINGS" ]; then
    echo >&2 'ERROR: This script must be called from within withGnuplotOutput.'
    exit 2
fi

DEBUGPREFIX=; case ",${DEBUG:-}," in *,withGnuplotOutput,*) DEBUGPREFIX=verbose;; *,withGnuplotOutput\!,*) DEBUGPREFIX=echotrace; WITHGNUPLOTOUTPUT_OPENFILE='';; esac
$DEBUGPREFIX "$WITHGNUPLOTOUTPUT_GNUPLOT_COMMAND" -e "$WITHGNUPLOTOUTPUT_TERMINAL_SETTINGS" "$@" || exit $?

[ -z "$WITHGNUPLOTOUTPUT_OUTPUTFILE" ] || printf '%s\n' "$WITHGNUPLOTOUTPUT_OUTPUTFILE"
[ -z "$WITHGNUPLOTOUTPUT_OPENFILE" ] || exec xdg-open "$WITHGNUPLOTOUTPUT_OPENFILE"
